### ISSUE TITLE
Help me to UnderStand this Project

### ISSUE THREAD

**Issue by dineshmerck** [brunellegrossmann/telemetry_opcua_exporter#1] opened 2021-02-05 12:22 UTC
@ahuret,

I am going to use this project for monitoring OPC UA Server.

Could you please help me how to check this project after run the main.go

I have installed Go and I am import this project into Visual Studio Code.

After that I ran go run main.go but I dont know whether its running or not.

Could you please help me on that. It will help me to understand on this project.

Regards,
Dinesh

**Comment by ahuret** [comment] 2021-02-05 12:47
Hi @dineshmerck !

Please check https://github.com/skilld-labs/telemetry-opcua-exporter/blob/master/README.md for entire configuration.

- define metrics configuration file : see https://github.com/skilld-labs/telemetry-opcua-exporter#metrics-configuration
- define server configuration by using flags: see https://github.com/skilld-labs/telemetry-opcua-exporter/blob/master/README.md#server-configuration
Is that help ?

**Comment by dineshmerck** [comment] 2021-02-08 04:55
@ahuret 
I have changed the configuration as per Readme file.

After that I ran "go run main.go".  But I didnt see the output, where I need to check.

Could you please help me how to check the result after ran the main.go.

Also please explain me if I add more metrics in OPCUA.yaml file it will work?

What is steps i need to follow if i want to add more metrics.

For Testing Purpose I have changed below metric,

metrics:
  - name: PLC
    help: get metrics for machine MaxNodesPerRead
    nodeid: ns=0;i=11705
    labels:
      site: Paris
    type: Float

**Comment by dineshmerck** [comment] 2021-02-08 05:05
> Hi @dineshmerck !
> 
> Please check https://github.com/skilld-labs/telemetry-opcua-exporter/blob/master/README.md for entire configuration.
> 
> * define metrics configuration file : see https://github.com/skilld-labs/telemetry-opcua-exporter#metrics-configuration
> * define server configuration by using flags: see https://github.com/skilld-labs/telemetry-opcua-exporter/blob/master/README.md#server-configuration
>   Is that help ?

I have modified @ahuret . I am able to run main.go but didnt see the output.

I can see the below in Terminal while running the main.go,

PS D:\Share\telemetry-opcua-exporter-master\telemetry-opcua-exporter-master> go run .\main.go
{"time": "2021-02-08T13:50:31.5555393+05:30", "level": "warn", "message": "No security mode is not recommended, consider using one"}

Could you please help me how to check the output of this project.

also pls let me know reason for the below message, I got that message in main.go file

	"message": "exported type SafeConfig should have comment or be unexported"

**Comment by ahuret** [comment] 2021-02-08 09:31
@dineshmerck,

Not sure you get the point of this repository: this is a telemetry exporter (prometheus implementation here).
Basically, it runs as a web server, waiting for prometheus server to scrap metrics.



> What is steps i need to follow if i want to add more metrics.

If you update the configuration file to add/remove metrics you can reload it (see https://github.com/skilld-labs/telemetry-opcua-exporter#reload-config-from-opcuayaml-file).
Also, you can modify the configuration file programmatically (see https://github.com/skilld-labs/telemetry-opcua-exporter#change-config-from-bodys-request-data).

> "....No security mode is not recommended, consider using one ....."

Security mode, security policy and authentication mode have to be defined according to configuration of your OPC UA server.
You can configure it using flags (see https://github.com/skilld-labs/telemetry-opcua-exporter#server-configuration).

> exported type SafeConfig should have comment or be unexported

This is a comment from your IDE (golang linter). As a best practice, golang recommands to comment exported types.

If you don't want to use a telemetry exporter, and just want to programatically get metrics, maybe should use https://github.com/gopcua/opcua directly, that's the golang library that helps interacts with OPC UA (telemetry-opcua-exporter is based on that library).

Hope that will help you ! :)

**Comment by dineshmerck** [comment] 2021-02-08 09:48
@ahuret 

127.0.0.1:4242/metrics -- > this is prometheus endpoint?

I have started the prometheus and its running in 9090.

Could you please let me know where should I point the prometheus end point

func main() {
	bindAddress := flag.String("bindAddress", ":4242", "Address to listen on for web interface")
	configPath := flag.String("config", "opcua.yaml", "Path to configuration file")
	endpoint := flag.String("endpoint", "opc.tcp://STLBIOPTS5ACE09:4840", "OPC UA Endpoint URL")

I have pointed my OPC UA Server

**Comment by ahuret** [comment] 2021-02-08 09:54
`127.0.0.1:4242/metrics` is the exporter endpoint prometheus should refer on to scrap metrics.

prometheus server endpoint has no relation with that exporter endpoint.

**Comment by dineshmerck** [comment] 2021-02-08 09:57
> `127.0.0.1:4242/metrics` is the exporter endpoint prometheus should refer on to scrap metrics.
> 
> prometheus server endpoint has no relation with that exporter endpoint.
My Config is ,

func main() {
	bindAddress := flag.String("bindAddress", ":4242", "Address to listen on for web interface")
	configPath := flag.String("config", "opcua.yaml", "Path to configuration file")
	endpoint := flag.String("endpoint", "opc.tcp://STLBIOPTS5ACE09:4840", "OPC UA Endpoint URL")

when I hit http://localhost:4242/metrics I got the below error,

An error has occurred while serving metrics:

error collecting metric Desc{fqName: "opcua_error", help: "error scraping target", constLabels: {}, variableLabels: []}: The operation could not complete because the client is not connected to the server. StatusBadServerNotConnected (0x800D0000).

In IDE I got the below error,

PS D:\Share\telemetry-opcua-exporter-master\telemetry-opcua-exporter-master> go run .\main.go
{"time": "2021-02-08T15:10:21.4061138+05:30", "level": "warn", "message": "No security mode is not recommended, consider using one"}
{"time": "2021-02-08T15:19:35.3334786+05:30", "level": "error", "message": "read failed: The operation could not complete because the client is not connected to the server. StatusBadServerNotConnected (0x800D0000)"}

**Comment by ahuret** [comment] 2021-02-08 09:58
So it means it cannot connect to the server. You should probably rework the Server Configuration part (auth-mode, sec-mode, sec-policy)

**Comment by dineshmerck** [comment] 2021-02-08 10:01
> So it means it cannot connect to the server. You should probably rework the Server Configuration part (auth-mode, sec-mode, sec-policy)

Pls see the below server details,

![image](https://user-images.githubusercontent.com/78598224/107204393-a4212500-6a22-11eb-87ac-e84fc3c89f8d.png)

Dont have those details what ever u have mentioned.

Please help me on that.

**Comment by ahuret** [comment] 2021-02-08 10:04
so it means you can connect with None sec policy, None sec mode, and Anonymous authentication.
You add add `debug` verbosity to get more details on why it fails

**Comment by dineshmerck** [comment] 2021-02-08 10:09
> so it means you can connect with None sec policy, None sec mode, and Anonymous authentication.
> You add add `debug` verbosity to get more details on why it fails

after add the debug

I can able to hit the localhost:4242/metric also able to see the below console in my IDE,

{"time": "2021-02-08T15:36:11.1924746+05:30", "level": "info", "message": "listening on address: :4242"}
{"time": "2021-02-08T15:37:05.93564+05:30", "level": "info", "message": "starting scrape"}
debug: uasc 2/4: send *ua.ReadRequest with 114 bytes
debug: conn 2: recv MSGF with 104 bytes
debug: uasc 2/4: recv MSGF with 104 bytes
debug: uasc 2/4: recv *ua.ReadResponse
debug: sending *ua.ReadResponse to handler
{"time": "2021-02-08T15:37:05.9426413+05:30", "level": "info", "message": "finished scrape, duration_seconds 0.0070011"}

after that what should I do

**Comment by ahuret** [comment] 2021-02-08 10:13
What do you mean by "what should I do" ?

**Comment by dineshmerck** [comment] 2021-02-08 10:16
> What do you mean by "what should I m

**Comment by dineshmerck** [comment] 2021-02-08 10:16
> What do you mean by "what should I do" ?

**Comment by dineshmerck** [comment] 2021-02-08 10:17
means how I will validate whether its working or not

**Comment by dineshmerck** [comment] 2021-02-08 10:18
> > What do you mean by "what should I do" ?

means how I will validate whether its working or not
 
in metrics I can see what ever i added,

# HELP PLC get metrics for machine MaxNodesPerRead
# TYPE PLC gauge
PLC{site="Paris"} 0

**Comment by ahuret** [comment] 2021-02-08 10:25
here `0` is the metric value, is it ok ?

**Comment by dineshmerck** [comment] 2021-02-08 10:29
> here `0` is the metric value, is it ok ?

how this value is coming.. its reading from node id what ever i have mentioned in yaml file?

metrics:
  - name: PLC
    help: get metrics for machine MaxNodesPerRead
    nodeid: ns=0;i=11705
    labels:
      site: Paris
    type: Float

**Comment by ahuret** [comment] 2021-02-08 10:32
Yep exactly, when the exported receive a signal (http get request) on http://127.0.0.1:4242/metrics , the exporter takes all metrics configuration from configuration file and scrap it in opc ua server.

prometheus -> exporter -> opcua server

**Comment by dineshmerck** [comment] 2021-02-08 10:38
> scrap it in opc ua server

as per my server that node id have value as 100
 then how it will show 0 in metrics

pls correct me if i m wrong

**Comment by ahuret** [comment] 2021-02-08 10:41
so it means there is surely something misconfigured. Maybe this is `nodeid: ns=0;i=11705` ?

**Comment by dineshmerck** [comment] 2021-02-08 10:42
> so it means there is surely something misconfigured. Maybe this is `nodeid: ns=0;i=11705` ?

![image](https://user-images.githubusercontent.com/78598224/107209067-632c0f00-6a28-11eb-98c6-5aa252c50707.png)

in Server, for that node id datatype is UInt32 but in the yaml file i have mentioned Float. is that because of that?

![image](https://user-images.githubusercontent.com/78598224/107209959-84412f80-6a29-11eb-871e-d767c651d39b.png)

**Comment by ahuret** [comment] 2021-02-08 11:04
I think the nodeid is not good. UAExpert have a special node id format.

**Comment by dineshmerck** [comment] 2021-02-08 11:24
> I think the nodeid is not good. UAExpert have a special node id format.

Sorry @ahuret didnt understand ur comment.

u meant to say ns=0;i=11075 is wrong node id

**Comment by ahuret** [comment] 2021-02-08 11:27
I mean: what UAExpert call "node id" is not the proper format for opc ua node id.
I think this is why it fails.

**Comment by dineshmerck** [comment] 2021-02-08 11:30
> I mean: what UAExpert call "node id" is not the proper format for opc ua node id.
> I think this is why it fails.

then pls guide me where i can get the correct node id from UAExporter
I tried some different node id as well.. but still i can see PLC{site="Paris"} 0

what could be the expected value?

**Comment by ahuret** [comment] 2021-02-08 11:37
please see http://documentation.unified-automation.com/uasdkhp/1.0.0/html/_l2_ua_node_ids.html

**Comment by dineshmerck** [comment] 2021-02-08 11:49
> please see http://documentation.unified-automation.com/uasdkhp/1.0.0/html/_l2_ua_node_ids.html

I have tried the below node id as well

![image](https://user-images.githubusercontent.com/78598224/107215718-b191db80-6a31-11eb-885f-d181e2d86e9e.png)

metrics:
  - name: PLC
    help: get metrics for machine Node Version
    nodeid: ns=1;i=1000
    labels:
      site: Paris
    type: gauge

still i m getting the same PLC{site="Paris"} 0

Value for that node id is 1

**Comment by ahuret** [comment] 2021-02-08 20:16
Have you try with ns=1;i=11707 as screenshot above ?

**Comment by jbguerraz** [comment] 2021-02-08 20:56
Since you are not encrypting the trafic you can easilly compare the communication between go-opcua and your opcua server and between uaexpert and your opcua server to find out what's different. Wireshark will help.

As far as I can see on https://github.com/skilld-labs/telemetry-opcua-exporter/issues/1#issuecomment-775030319 the communication goes well. It must be a configuration issue.

Looks like the code here works as intended (it requests the opcua server and answers prometheus scrape).

Closing it since no action required on the opcua exporter side.

**Closed as completed by jbguerraz** 2021-02-08 20:56 UTC

**Comment by dineshmerck** [comment] 2021-02-09 09:04
> Have you try with ns=1;i=11707 as screenshot above ?

@ahuret  yes.. I have tried the ns=1;i=11707
